### ISSUE TITLE
Forgot to change the copyright

### ISSUE THREAD

**Issue by AlliotTech** [huaweicloud/cloudeye-exporter#64]
https://github.com/huaweicloud/cloudeye-exporter/blob/a69f6fc1c45725ade0498a320e464cbab15ca887/grafana_dashboard/templates/dcs_dashboard_template.json#L28C15-L28C42

<img width="744" alt="image" src="https://github.com/huaweicloud/cloudeye-exporter/assets/24980252/6533bcd5-ef62-4f84-8022-548c61caeebe">

**Comment by cxl123156** [comment]
deleted , thanks
